# Generated by Django 3.1.2 on 2020-12-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0021_auto_20201201_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='results',
            name='test',
            field=models.CharField(default='a', max_length=2),
        ),
    ]
