# Generated by Django 3.1.2 on 2020-12-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0022_auto_20201203_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=500, null=True)),
                ('studid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mu.stud')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mu.multi')),
            ],
            options={
                'ordering': ['testid'],
            },
        ),
    ]
