# Generated by Django 3.1.2 on 2020-12-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mu', '0023_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
